### PR TITLE
Actuator disk first pass

### PR DESCRIPTION
**Pull request by psakievich**
First pass at the actuator disk implementation.  

Still working through the concepts a bit.

### CODE REVIEW

**Comment by sayerhs** [comment]
Why are OpenFAST files tracked within the main source code? This a really bad idea. I also think replicating the nalu set-up for OpenFAST files is not the way to go. We should be taking OpenFAST files directly from the OpenFAST r-test repo.

**Comment by psakievich** [comment]
That is for convenience while I work through the tests.  I already had plans to make a common infrastructure for both codes wrt OpenFAST files but I don't have time to implement it right now.

**Comment by michaeljbrazell** [comment]
@psakievich can you add a regression test to this PR?

**Comment by michaeljbrazell** [comment]
> @psakievich can you add a regression test to this PR?

Thanks for the quick chat, let's hold off on adding the regression test. When Jon gets back we can discuss how to incorporate openfast.

**Review by michaeljbrazell — APPROVED** [review]

**Pull request merged**
