### PR TITLE
Thermal expansion coefficient and ref temp consolidation

### PR DESCRIPTION
**Pull request by marchdf**
## Summary

Consolidate the thermal expansion coefficient and reference temperature. Make both of these fields, except some uses of ref temp in rare cases where one needs a single value (e.g. for stats).

## Pull request type

Please check the type of change introduced:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

The following is included:

- [ ] new unit-test(s)
- [ ] new regression test(s)
- [ ] documentation for new capability

This PR was tested by running:

- the unit tests
  - [x] on GPU 
  - [x] on CPU 
- the regression tests
  - [x] on GPU 
  - [x] on CPU

### CODE REVIEW

**Comment by hgopalan** [comment]
This assumes user specifies thermal_expansion_coeff but what if reference_temperature is specified instead?

**Comment by marchdf** [comment]
Nothing to see here for now. Don't worry, I will get there.

**Comment by marchdf** [comment]
Diffs I am seeing on CPU:
```
The following tests FAILED:
         31 - abl_multiphase_laminar (Failed)   -> large diffs
         32 - act_abl_joukowskydisk (Failed)    -> machine diffs, except p and gp at 1e-9
         33 - act_abl_uniformctdisk (Failed)    -> machine diffs, except p and gp at 1e-9
         62 - abl_amd_wenoz (Failed)            -> machine diffs
         76 - ow_stokes (Failed)                -> machine diffs
         92 - forest_drag (Failed)              -> 1e-9 diffs
        107 - abl_kosovic_neutral (Failed)      -> machine diffs, except p and gp at 1e-2
        109 - abl_kosovic_neutral_ib (Failed)   -> machine diffs, except p and gp at 1e-9
        110 - nrel_precursor (Failed)            -> machine diffs, except p and gp at 1e-9
        111 - abl_wallrans_neutral (Failed)       -> machine diffs
        125 - abl_multiphase_w2a (Failed)        -> large diffs
        139 - nrel_terrain (Not Run)
        140 - nrel_terrain_amr (Not Run)
```

Need to investigate `abl_multiphase_w2a` and `abl_multiphase_laminar`

**Comment by marchdf** [comment]
Down to these:
```
The following tests FAILED:
         32 - act_abl_joukowskydisk (Failed)  -> machine diffs, except p and gp at 1e-9
         33 - act_abl_uniformctdisk (Failed)     -> machine diffs, except p and gp at 1e-9
         62 - abl_amd_wenoz (Failed)                -> machine diffs
         92 - forest_drag (Failed)                        -> 1e-9 diffs
        107 - abl_kosovic_neutral (Failed)         -> machine diffs, except p and gp at 1e-2
        109 - abl_kosovic_neutral_ib (Failed).   -> machine diffs, except p and gp at 1e-2
        110 - nrel_precursor (Failed)                    -> machine diffs, except p and gp at 1e-9
        111 - abl_wallrans_neutral (Failed)           -> machine diffs
        139 - nrel_terrain (Not Run)
        140 - nrel_terrain_amr (Not Run)
```
I am fine with pressure and gp diffs. The higher diffs in forest drag are due to the fact that the tolerance on the solver are not tight.

**Comment by marchdf** [comment]
Just a heads up. This is going to cause warnings with older input files. They will still run fine. But the warnings will educate the user on how to update the input file so that the warnings go away.

**Comment by marchdf** [comment]
Ok that last tweak made all tests pass except 2:
```
The following tests FAILED:
         62 - abl_amd_wenoz (Failed)
        111 - abl_wallrans_neutral (Failed)
```
which are machine diffs. So we are good.

**Review by mbkuhn — APPROVED** [review]
incredible stuff.

**Pull request merged**
