### PR TITLE
Documentation of ALM calibration in walkthrough

### PR DESCRIPTION
**Pull request by gyalla**
## Summary

Adding sphinx documentation to the walkthrough section for actuator line model calibrations

Please check the type of change introduced:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by gyalla** [comment]
When I build the documentation with sphinx, the "Actuator Line Model Calibration" section shows up under "Walkthrough", but it disappears if I go to other sections like "LES with Terrain" (see below). How can I keep it in the sidebar permanently? 


Screenshot 2024-10-24 at 9 56 06 AM

Screenshot 2024-10-24 at 9 56 15 AM

**Comment by marchdf** [comment]
Nice work! 

I have that happen in local builds as well sometimes. It has to do with the browser and the way it is caching things I think. I think it will be fine once all is build for the website.

**Comment by marchdf** [comment]
You have a couple of typos (see the CI). For jupyter and aerodyn you can add those to the exception list: https://github.com/Exawind/amr-wind/blob/main/docs/sphinx/spelling-wordlist.txt. I try to keep that list alphabetized.

**Review by mbkuhn — APPROVED** [review]
This will be a great addition to the docs.

**Pull request merged**
