### PR TITLE
update amrex submod

### PR DESCRIPTION
**Pull request by baperry2**
Update the AMReX submodule. A couple minor updates are needed to handle changes that have been made in AMReX.

### CODE REVIEW

**Comment by baperry2** [comment]
@jrood-nrel any idea why this is causing clang-tidy to complain?

**Comment by jrood-nrel** [comment]
I'm guessing `AMREX_SPACEDIM` is not a macro anymore.

**Comment by jrood-nrel** [comment]
Oh maybe they promoted some types in their data structures to `long`.

**Comment by baperry2** [comment]
There were changes to how `AMREX_SPACEDIM` gets defined in https://github.com/AMReX-Codes/amrex/pull/3309 that appear to be causing this to now get caught by clang-tidy. In any event, I just implemented the fixes that clang-tidy recommends.

**Pull request merged**
