### PR TITLE
Hurricane Temperature forcing

### PR DESCRIPTION
**Pull request by gdeskos**
Implementing a hurricane forcing term for the temperature equation

- This PR includes a unit-test. Current unit-tests passes because it calculates everything to zero. Need to revisit the golds.

### CODE REVIEW

**Comment by mchurchf** [comment]
Yorgos, thanks for implementing this.  My main comment is do we really need this forcing to be something that is specified separate from `hurricaneForcing`.  I'd just make this temperature forcing come on always if hurricane forcing is specified, but it can default that dT/dr = 0, so if the user doesn't input it, it has no effect.  Also, dT/dr is a constant in this implementation.  Is that true of dV/dR?  To be more realistic, we should be able to specify dV/dR and dT/dR as functions of z, if not also functions of time (but that could come as a new pull request soon).

**Review by mchurchf — COMMENTED** [review]
See my comment in the comments section.

**Comment by gdeskos** [comment]
1. Agree that this is ugly, but I am not sure if we can initialize the hurricane forcing for the temperature from the ICNS one. You see the way source terms are setup at the moment they require to separate them by the equation they are applied. If dT/dr is zero then no need to add a source term to the potential temperature equation. 
2.dT/dr is a constant for simplicity. It should be (like dV/dR) a function of z. This is easy to change. Do you have an idea of how dT/dr varies vertically (based on the data that Miguel shared with us?)

**Review by mchurchf — APPROVED** [review]
I approve!  Thank you, Yorgos.

**Review by mchurchf — APPROVED** [review]

**Review by mbkuhn — APPROVED** [review]

**Pull request merged**
