### PR TITLE
Fixing RegTest for Terrain 

### PR DESCRIPTION
**Pull request by hgopalan**
## Summary

Broke the previous PR trying to rebase. Clean RegTest 

## Pull request type

Please check the type of change introduced:

- [ X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

The following is included:

- [ ] new unit-test(s)
- [ ] new regression test(s)
- [ ] documentation for new capability

This PR was tested by running:

- the unit tests
  - [ ] on GPU 
  - [ ] on CPU 
- the regression tests
  - [ ] on GPU 
  - [ ] on CPU 

Issue Number: #1289

### CODE REVIEW

**Comment by marchdf** [comment]
Here's what I am seeing:
- Looks like the `terrain_box` issue is fixed, except I am seeing:
```
Unused ParmParse Variables:
  [TOP]::DragForcing.verificationMode(nvals = 1)  :: [1]
```
Could you remove that line from `test/test_files/terrain_box/terrain_box.inp` ? 

- `nrel_terrain` looks like it is using a restart:
```
Initializing I/O manager
Restarting from checkpoint ../nrel_precursor/chk02000
terminate called after throwing an instance of 'std::runtime_error'
  what():  Couldn't open file: ../nrel_precursor/chk02000/Header
SIGABRT
See Backtrace.0 file for details
```

Can you remove the restart line from that input file?

Thanks!!

**Review by marchdf — CHANGES_REQUESTED** [review]
Minor edits requested, see my comment.

**Comment by hgopalan** [comment]
The regtests ran in less than a minute on 10 procs locally.

**Review by marchdf — APPROVED** [review]

**Comment by marchdf** [comment]
Everything runs to completion now.

**Pull request merged**
