### PR TITLE
Add verfication test category and add MMS 2nd order verification test

### PR DESCRIPTION
**Pull request by jrood-nrel**
This allows anyone to run @marchdf 's MMS 2nd order verification. This test does require many Python packages to be available at run time, such as matplotlib and pandas. The test produces a `plots.pdf` file and is uploaded to CDash. Currently the python script doesn't appear to automatically check for 2nd order, so the test passes if the PDF is generated. Probably should add such a check in the future.

### CODE REVIEW

**Comment by sayerhs** [comment]
So I suppose this means I've to train myself to add `-LE verification` with my CTest runs when developing on Mac?

**Comment by jrood-nrel** [comment]
Yeah I feel the same way. Is there a way to not run a test by default? Let me look.

**Comment by sayerhs** [comment]
I think that would require an `AMR_WIND_ENABLE_VERIFICATION_TESTS` flag?

**Comment by jrood-nrel** [comment]
Yeah the only thing for test properties I see is explicitly setting a test to disabled, which won't work. I guess that's why I have an `ENABLE_MASA` and `ENABLE_VERIFICATION` in Pele. I can add it back in if you would rather do it that way.

**Comment by sayerhs** [comment]
Let's try out the pull-request as it stands for a while. If it feels too painful, we can revisit and add the CMake option to disable it.

**Pull request merged**
