### PR TITLE
Actuators: sample mac velocity instead of cell-centered velocity

### PR DESCRIPTION
**Pull request by mbkuhn**
goal of this is to sample velocity at n-1/2, advance timestep by a dt, apply forces at n+1/2

### CODE REVIEW

**Comment by tonyinme** [comment]
Thanks @mbkuhn ! 
@gdeskos and @mchurchf , this is the latest development/test for the ALM based on our conversations.

**Comment by tonyinme** [comment]
Hi all, just wanted to add that this PR has improved the advanced ALM results significantly. 
The conversations with the team have suggested that this should become the standard way of implementing ALM body forces (velocity sampled at n-1/2 and forces implemented at n+1/2).

**Comment by mbkuhn** [comment]
Because we haven't yet tested this for other actuator types (e.g. disk), I made the new sampling approach an option that is turned on by an input argument, Actuator.sample_vel_nmhalf = true

**Review by tonyinme — COMMENTED** [review]
These changes look great.
I think it is best to set the mac velocity as a default, because it is actually a bug fix. 
We might want/need to remove the legacy code eventually.

**Comment by lawrenceccheung** [comment]
My apologies I should have added this earlier, can this also be the default for `TurbineFastDisk`?  We believe it could also be important for OpenFAST ADM cases.

Lawrence

**Comment by mbkuhn** [comment]
At this point, I think it has the default behavior as desired.

**Comment by tonyinme** [comment]
Hey @mbkuhn , that's excellent!
You can add the option to the documentation, and merge.

**Pull request merged**
