### PR TITLE
in apply_bcs, only perform fillphysbc for new time

### PR DESCRIPTION
**Pull request by mbkuhn**
## Summary

Avoid filling physbc at old times, they should already be filled. Necessary for #1302.

## Pull request type

Please check the type of change introduced:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

The following is included:

- [ ] new unit-test(s)
- [ ] new regression test(s)
- [ ] documentation for new capability

This PR was tested by running:

- the unit tests
  - [ ] on GPU 
  - [ ] on CPU 
- the regression tests
  - [ ] on GPU 
  - [ ] on CPU 

## Additional background

Should introduce no diffs, but may introduce diffs for abl_godunov_wenoz_fixedpt. However, this part of the algorithm needs to be adjusted for fixed point iterations, which I've talked to Ilker about.

### CODE REVIEW

**Comment by mbkuhn** [comment]
The reason why this needs to be adjusted is the compute_diff_term always operates on the new state, even when the values are old. This isn't necessary; we should be able to operate on the old state, and that would fix things.

**Comment by mbkuhn** [comment]
I'm thinking I'll add that tweak to this PR

**Comment by marchdf** [comment]
I am seeing these fail:
```
The following tests FAILED:
          7 - abl_godunov_mpl (Failed)
          8 - abl_godunov_mpl_amr (Failed)
         60 - abl_godunov_wenoz_fixedpt (Failed)
        121 - abl_bndry_input_native (Failed)
        123 - abl_bndry_input_amr_native (Failed)
        124 - abl_bndry_input_amr_native_xhi (Failed)
        125 - abl_bndry_input_amr_native_mlbc (Failed)
        126 - abl_godunov_forcetimetable (Failed)
        127 - abl_bndry_input (Failed)
        128 - abl_bndry_input_amr (Failed)
        129 - abl_bndry_input_amr_inflow (Failed)
        130 - nrel_terrain (Failed)
```
The fixedpt one is just missing golds. Not sure about the others.

**Comment by mbkuhn** [comment]
I think these all make sense, actually. The boundary planes are all currently hard-coded to use new_time when there is a fillphysbc. Therefore, when apply_bcs takes place at the old time, it puts new data in to the boundaries of the new state, which hasn't been updated yet, so it is just old data with new boundaries. This PR takes that away.

Ok, well, one thing that pokes a hole in this is that many of these cases have incflo.diffusion = 2, which means it's pure implicit. Not sure what compute_diff_term is doing in that case, gonna have to investigate further.

**Comment by mbkuhn** [comment]
Ok, I stand by my original theory. Even though many of these use implicit diffusion, the mac projection still uses the explicit diffusion calculation. The diffs only show up where the boundaries are coded to update (even when they shouldn't, at old times).

**Comment by mbkuhn** [comment]
Supporting evidence:
if I change the state to "New" instead of "Old" in this line, then the diffs go away. The changes only prep diffusion terms for the MAC extrapolation step.
https://github.com/Exawind/amr-wind/blob/main/amr-wind/incflo_advance.cpp#L250

**Pull request merged**
