### PR TITLE
First cut at examples read-the-docs page.  Adding inflow-outflow example.

### PR DESCRIPTION
**Pull request by neilmatula**

### CODE REVIEW

**Comment by tonyinme** [comment]
hey @neilmatula , the documentation is good. I was thinking it might be worth adding towards the end the commands used to run the code (including the number of processors recommended).

**Comment by neilmatula** [comment]
@tonyinme Sounds good.  I'll add that.

**Review by lawrenceccheung — COMMENTED** [review]
Hi @neilmatula, this is great.  I really like the schematic showing the different stages of the inflow/outflow run.

I was wondering if it's possible to show snippets of the log file during a successful run.  Maybe something like the start of the log file, the first iteration and the end of the log file so people know what it looks like when amr-wind is running properly.  It doesn't have to be for this example case, could be for the other ones too.

Thanks,

Lawrence

**Comment by neilmatula** [comment]
@lawrenceccheung 
Yep.  I'll add that.

**Review by tonyinme — APPROVED** [review]
This looks good.
Is anything missing?
Or can it be merged?

**Comment by jrood-nrel** [comment]
This references and `examples` directory that doesn't exist.

**Comment by neilmatula** [comment]
Pinging for activity.

**Comment by marchdf** [comment]
@neilmatula what are your thoughts on pushing this through? Do you need a hand?

**Comment by neilmatula** [comment]
@marchdf With a bit more work it can be pushed through.
Thanks, but I think I can do it myself soon.

One remaining concern is ABLMeanBoussinesq.
My current thinking is that it needs to be turned on for both precursor and inflow-outflow.
If it's just turned on for the latter, strange effects can be observed in both pressure and the mean velocities.
I'd like to confirm that having it on for both is what we should be doing.  Also, if that's the case, can we guard against someone accidentally not doing that?

**Comment by lawrenceccheung** [comment]
In one of my last conversations with Mike B., we mentioned that the ultimate solution is to have a better outflow BC which doesn't rely on `ABLMeanBoussinesq` being turned on.  (Ideally we'd do this with other planned MMC coupling type work).  However, in the absence of that, we should turn on `ABLMeanBoussinesq` in precursors because people are likely to forget about it in their normal workflows.

Lawrence

**Pull request closed without merging**
