### PR TITLE
Enable int field refinement

### PR DESCRIPTION
**Pull request by marchdf**
## Summary

Enable int field refinement for the user.  For example, tagging on terrain blanking:

Screenshot 2024-11-18 at 10 47 49 AM

@mbkuhn This should also work with the multiphase stuff your were talking about last week. 

## Pull request type

Please check the type of change introduced:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

The following is included:

- [x] new unit-test(s)
- [x] new regression test(s)
- [ ] documentation for new capability

This PR was tested by running:

- the unit tests
  - [ ] on GPU 
  - [ ] on CPU 
- the regression tests
  - [ ] on GPU 
  - [ ] on CPU

### CODE REVIEW

**Comment by marchdf** [comment]
Wait for #1353 to merge

**Comment by marchdf** [comment]
No documentation needed because our current documentation is misleading in that in does not distinguish int vs normal fields for refinement ;)

**Comment by mbkuhn** [comment]
love it, well done. do you know if it would be easy to add refinement based on derived fields? I don't need it, but I could see that being useful, and I know we added both int and derived fields to the sampling recently. If it's not straightforward, though, I'd wait until someone requests it.

**Review by mbkuhn — APPROVED** [review]

**Comment by marchdf** [comment]
It might be useful but it's a bit annoying. Derived fields are `ScratchFields`. So now you need to parse that, populate the scratch field and then you can refine it. And they are a different type than `Field` or `IntField` so you have to be even more clever with what the "FieldRefinement" has in its member vars.  

I don't like what I had to do with the `m_field` and `m_int_field` but we don't have a base class for fields that would help with templating (which is what I initially tried). It gets messy quick. Mostly because at heart, `MultiFAB` and `iMultiFAB` are completely separate classes so that propagates down the line.

**Pull request merged**
