### PR TITLE
Add wall model capability to x and y boundaries

### PR DESCRIPTION
**Pull request by michaeljbrazell**
- adds wall model capability to x and y boundaries
- removes extrapolate for velocity and density since we want to evaluate velocities at cell center
- this function will be removed once we add the general version that works for arbitrary heights

### CODE REVIEW

**Comment by michaeljbrazell** [comment]
What should we do with density?

**Comment by sayerhs** [comment]
Is there any way to reduce the code duplication? Not critical for this pull request as it would be eventually replaced by the new algorithm, but we will have to deal with it for the new one and other places.

**Comment by sayerhs** [comment]
Also, by density do you mean the nph stuff?

**Comment by michaeljbrazell** [comment]
I'll take a stab at reducing duplication. I was thinking about the density in the mu*dudz = rho*utau^2 term

**Pull request merged**
