### PR TITLE
Spinner: first pseudo-code

### PR DESCRIPTION
**Pull request by tonyinme**
This is a draft PR to get some feedback on the implementation.
A spinner lidar samples at a very high frequency (much smaller than simulation time-step).
The idea is to sample many lines within a time-step with only one container.
This is done by setting the number of particles in the container (for this sampler) to be as big as the number of points in the line times the number of samples during the time-step.
The current pseudo-code has some bugs which need to be fixed.

- [x] Fix bugs

### CODE REVIEW

**Comment by tonyinme** [comment]
I have made changes to the code. This is now a working version. At every CFD time-step, all the points are output together, as opposed to individual lines.

**Comment by jrood-nrel** [comment]
@tonyinme Can you take care of all the warnings shown in the files changed tab?

**Comment by tonyinme** [comment]
Thanks @jrood-nrel , I have modified the files accordingly.

**Comment by tonyinme** [comment]
@jrood-nrel and @sayerhs , this capability is ready. Let me know if any changes are required before merging. Some of the checks fail but these are unrelated to the current PR and I believe have been fixed recently.

**Review by jrood-nrel — APPROVED** [review]

**Comment by mchurchf** [comment]
Hi Tony.  Other than these failing checks, I approve this, and I think it should be merged and run through its paces and updated.

**Review by michaeljbrazell — APPROVED** [review]
looks good

**Pull request merged**
