### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by marchdf**
Automatically create PRs when certain submodules change. We can then decide whether to merge. More automation possible using instructions here: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

### CODE REVIEW

**Review by jrood-nrel — APPROVED** [review]

**Comment by sayerhs** [comment]
@marchdf Is the intent to create a PR for ever commit that AMReX has? You might want to add a check on the release tags for AMReX and hydro submodules, otherwise this is going to create a lot of unnecessary noise.

**Comment by jrood-nrel** [comment]
https://github.com/Exawind/amr-wind/blob/fae858477bb8023a62369e8753ac774d992f6183/.github/dependabot.yml#L6

**Comment by marchdf** [comment]
Yeah this will just check weekly and then update to latest. So the noise is a weekly PR. If you dont do anything with that PR, the next PR will close the old one and open a new one.

**Comment by sayerhs** [comment]
Ah I see. I didn't catch the fact that the previous PR will automatically be closed upon a new PR being created. Thanks for clarifying that.

**Pull request merged**
